version: '3.4'

services:
  inno_shop.services.users:
    image: ${DOCKER_REGISTRY-}innoshopservicesusers
    build:
      context: .
      dockerfile: Inno_Shop.UsersMicroservice/Dockerfile
   

  inno_shop.services.products:
    image: ${DOCKER_REGISTRY-}innoshopservicesproducts
    build:
      context: .
      dockerfile: Inno_Shop.ProductsMicroservice/Dockerfile


