version: '3.4'


networks:
  backend:


services:
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend


  usermanagement.service:
    container_name: users-service
    image: ${DOCKER_REGISTRY-}usermanagementservice
    build:
      context: .
      dockerfile: UserManagement.Service/Dockerfile
    networks:
      - backend


  productmanagement.service:
    container_name: products-service
    image: ${DOCKER_REGISTRY-}productmanagementservice
    build:
      context: .
      dockerfile: ProductManagement.Service/Dockerfile
    networks:
      - backend

  userdb:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend

  productdb:
    container_name: product-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8003:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend

